### ISSUE TITLE
Problem converting pcap to csv file

### ISSUE THREAD

**Issue by YellowFlowerHuaHua** [maliksh7/CapCSV-meter#1]
Tried to run this via a python script on terminal in linux

from flowmeter import Flowmeter

feature_gen = Flowmeter(
    offline = "input.pcap",
    outfunc = None,
    outfile = "output.csv")

feature_gen.run()

The following was returned

daddy@daddy-virtualbox:~/Desktop/CapCSV-meter-main$ python3 run_flowmeter.py
/home/daddy/Desktop/CapCSV-meter-main/flowmeter/flowmeter.py:1697: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self._sess_frames[sess] = self._sess_frames[sess].append(dict(zip(fields, row)), ignore_index=True)
/home/daddy/Desktop/CapCSV-meter-main/flowmeter/flowmeter.py:1697: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self._sess_frames[sess] = self._sess_frames[sess].append(dict(zip(fields, row)), ignore_index=True)
/home/daddy/Desktop/CapCSV-meter-main/flowmeter/flowmeter.py:1697: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self._sess_frames[sess] = self._sess_frames[sess].append(dict(zip(fields, row)), ignore_index=True)
/home/daddy/Desktop/CapCSV-meter-main/flowmeter/flowmeter.py:1697: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self._sess_frames[sess] = self._sess_frames[sess].append(dict(zip(fields, row)), ignore_index=True)
/home/daddy/Desktop/CapCSV-meter-main/flowmeter/flowmeter.py:1697: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self._sess_frames[sess] = self._sess_frames[sess].append(dict(zip(fields, row)), ignore_index=True)
/home/daddy/Desktop/CapCSV-meter-main/flowmeter/flowmeter.py:1697: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self._sess_frames[sess] = self._sess_frames[sess].append(dict(zip(fields, row)), ignore_index=True)
/home/daddy/Desktop/CapCSV-meter-main/flowmeter/flowmeter.py:1697: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self._sess_frames[sess] = self._sess_frames[sess].append(dict(zip(fields, row)), ignore_index=True)
192.168.208.3:80<->192.168.208.7:80,192.168.208.3,80,192.168.208.7,58044,TCP,0.0,1,1,0,66,0,66,66,66.0,0.0,0,0,0.0,0.0,66.0,1,0.0,0.0,0,0,0,0.0,0.0,1652676218.368337,1652676218.368337,0,0.0,0.0,1652676218.368337,0,0,0,0,0,0,0,1,1,66,66,66.0,0.0,0.0,1,0,0,0,1,0,0,0,1,66.0,0.0,0.0,0,0,0,0,0,0,1.0,66.0,0.0,0.0,506,0,1,52,0.0,0.0,0.0,0.0,0,0,0,0,None

192.168.208.7:58044<->192.168.208.3:58044,192.168.208.7,58044,192.168.208.3,80,TCP,0.0,1,1,0,66,0,66,66,66.0,0.0,0,0,0.0,0.0,66.0,1,0.0,0.0,0,0,0,0.0,0.0,1652676218.368261,1652676218.368261,0,0.0,0.0,1652676218.368261,0,0,0,0,0,0,0,1,1,66,66,66.0,0.0,0.0,1,0,0,0,1,0,0,0,1,66.0,0.0,0.0,0,0,0,0,0,0,1.0,66.0,0.0,0.0,501,0,1,52,0.0,0.0,0.0,0.0,0,0,0,0,None

/home/daddy/Desktop/CapCSV-meter-main/flowmeter/flowmeter.py:1697: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self._sess_frames[sess] = self._sess_frames[sess].append(dict(zip(fields, row)), ignore_index=True)
/home/daddy/Desktop/CapCSV-meter-main/flowmeter/flowmeter.py:1697: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self._sess_frames[sess] = self._sess_frames[sess].append(dict(zip(fields, row)), ignore_index=True)
/home/daddy/Desktop/CapCSV-meter-main/flowmeter/flowmeter.py:1697: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self._sess_frames[sess] = self._sess_frames[sess].append(dict(zip(fields, row)), ignore_index=True)
/home/daddy/Desktop/CapCSV-meter-main/flowmeter/flowmeter.py:1697: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self._sess_frames[sess] = self._sess_frames[sess].append(dict(zip(fields, row)), ignore_index=True)
/home/daddy/Desktop/CapCSV-meter-main/flowmeter/flowmeter.py:1697: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self._sess_frames[sess] = self._sess_frames[sess].append(dict(zip(fields, row)), ignore_index=True)
/home/daddy/Desktop/CapCSV-meter-main/flowmeter/flowmeter.py:1697: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self._sess_frames[sess] = self._sess_frames[sess].append(dict(zip(fields, row)), ignore_index=True)
/home/daddy/Desktop/CapCSV-meter-main/flowmeter/flowmeter.py:1697: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self._sess_frames[sess] = self._sess_frames[sess].append(dict(zip(fields, row)), ignore_index=True)
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/usr/local/lib/python3.8/dist-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/daddy/Desktop/CapCSV-meter-main/flowmeter/flowmeter.py", line 1697, in process_packet
    self._sess_frames[sess] = self._sess_frames[sess].append(dict(zip(fields, row)), ignore_index=True)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 9039, in append
    return self._append(other, ignore_index, verify_integrity, sort)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 9082, in _append
    result = concat(
  File "/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/concat.py", line 360, in concat
    return op.get_result()
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/concat.py", line 591, in get_result
    indexers[ax] = obj_labels.get_indexer(new_labels)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py", line 3721, in get_indexer
    raise InvalidIndexError(self._requires_unique_msg)
pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_flowmeter.py", line 5, in <module>
    feature_gen.run()
  File "/home/daddy/Desktop/CapCSV-meter-main/flowmeter/flowmeter.py", line 174, in run
    Parallel(-1)(delayed(self.process_packet)(packet) for packet in reader)
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.8/dist-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python3.8/dist-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
pandas.errors.InvalidIndexError: Reindexing only valid with uniquely valued Index objects

i think there's some problem with the library but i'm unable to correct it myself.

**Comment by AlirezaDehlaghi** [comment]
I have similar issue
Reindexing only valid with uniquely valued Index object

**Comment by maliksh7** [comment]
> I have similar issue Reindexing only valid with uniquely valued Index object

**Comment by maliksh7** [comment]
you must install all requiremts.txt tools
